#!/bin/bash
#SBATCH --job-name=MOCO_LINEAR   # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=4        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem=128G                 # total memory per node (4 GB per cpu-core is default)
#SBATCH --partition=gpu-he --gres=gpu:4
#SBATCH --time=95:59:59          # total run time limit (HH:MM:SS)
#SBATCH --mail-type=begin        # send mail when job begins
#SBATCH --mail-type=end          # send mail when job ends
#SBATCH --mail-type=fail         # send mail if job fails
#SBATCH --mail-user=slurmstatus@gmail.com

export PY=/users/pyu12/.conda/envs/gpu/bin/python3.8

#module purge
module load anaconda/2020.02
#conda init bash
source ~/.bashrc
conda activate gpu

$PY main_lincls.py \
      -a resnet50 \
      --lr 30.0 \
      --batch-size 256 \
      --pretrained /users/pyu12/data/pyu12/models/moco/moco_v2_800ep_pretrain.pth.tar \
      --dist-url 'tcp://localhost:10001' --multiprocessing-distributed --world-size 1 --rank 0 \
      /users/pyu12/data/pyu12/datasets/ILSVRC/


for file in ./*.tar
do
    echo ${file%%.tar}
    tar xvf "${file%%.tar}".tar
done